server:
  port: 2020

spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://47.94.232.155:3306/testD1?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    test2:
      jdbc-url: jdbc:mysql://47.94.232.155:3306/testD2?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root

mybatis:
  mapper-locations: classpath*:/mapper/**.xml